# Generated by Django 5.1.1 on 2024-10-05 04:57

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.FileField(
                blank=True, null=True, upload_to=accounts.models.profile_picture_path
            ),
        ),
    ]
