# Generated by Django 5.1.1 on 2024-10-06 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0002_remove_upvoteaction_deleted_at_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply_to_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply_comments",
                to="suggestions.comment",
            ),
        ),
    ]
